### ISSUE TITLE
Re-license under Apache 2.0

### ISSUE THREAD

**Issue by mhei** [DevCodeOne/udevpp#1]
There is a tiny C++ library https://github.com/zeroping/sysfspwm which uses your udevpp one. However, sysfspwm's license is Apache-2.0 which is not compatible with your GPL-3 according to my understanding (disclaimer: I'm no license expert nor lawyer). My cheeky question: would you mind re-license your library under Apache 2.0 ?

**Comment by DevCodeOne** [comment]
Yes, that would be correct. I changed the license. To be honest I don't care too much about it anyway.
I used it so all people that want to use it and make changes to it, have to make the changes available for everyone.
Since it's such a small library it's ok for me.
